### ISSUE TITLE
Fix performance exploit involving profile images

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#104]
> Oh, by the way. One thing y'all might want to try to patch at some point would be putting caching on the /pp/ route for profile images. It's probably the most severe active bug we have at the moment. If someone @ pings a large number of users N, every page load winds up making N DB transactions with rather expensive ORM work

**Comment by TLSM** [comment]
A particularly bad instance of this bug (though it reliably happens whenever someone mass-pings) can be seen in the following. This had every CPU core maxed out for the better part of an hour until we removed the comments and temp-banned the author. Based on investigating the request pipeline, we're fairly confident it's in the /pp/ route; however, our profiling tooling isn't quite good enough to say for certain.

![](https://i.imgur.com/UouIxtp.png)

**Comment by mjhouse** [comment]
I'm going to add the @mention feature to the markdown preview and then use [Flask-Caching](https://flask-caching.readthedocs.io/en/latest/) on the `/pp/` route and `/@<username>/pic` routes.

**Comment by mjhouse** [comment]
I've got the markdown preview mentions working and caching enabled on the `/pp/` and `/@<username>/pic` routes. Now I just need a way to generate about a thousand test accounts with profile pictures.

![mention_preview_demo](https://user-images.githubusercontent.com/4141157/172152413-23066805-ad35-4e1f-9a29-ed83eb42b6c1.gif)

**Comment by mjhouse** [comment]
Side note- there was a bug where, after posting, server side mention-link generation would match only part of a username. So `@mm120` became `<a href="/pp/<id for mm12>">@mm12</a>0`. I've pulled in a change that fixed this bug from the rDrama repo ([0d9c40f4c903aa9e52149c997620d3ad4447d85d](https://github.com/Aevann1/rDrama/commit/0d9c40f4c903aa9e52149c997620d3ad4447d85d)).

**Comment by mjhouse** [comment]
## Problem

When a large number of mentions are included in a single post (or in replies that all appear on the same page), the browser pings the `/pp/<id>` endpoint for every single one of them. The endpoint queries the database for a user, gets the users profile_url and returns a redirect to it. The browser then queries the server again for the image and displays it in the page. 

## Testing

Testing was done with 500 unique users loaded into the database via a helper script, all of whom had a unique profile image in an `images/test/` directory location. All of the images are the same image but copied to 500 unique locations via a bash script. The post content was generated with another bash script. The end result was this test post:

![image](https://user-images.githubusercontent.com/4141157/172474156-f816a0e4-4667-4e92-96e4-9b4e50564973.png)

## Causes

1. I think part of the load is just due to the large number of images being requested and is probably unavoidable. It may be worth putting a cap on the number of mentions *allowed* in a post and rejecting the submission if someone tries to do this.
2. Another part is obviously the database query for the user, although this was surprisingly quick.
3. Maybe not related to CPU usage as much, but the redirect that the `/pp/` route was returning causes the browser to have to ping the server twice as many times, which noticeably degrades performance.
4. Lastly, I think that it's possible the redirect to the profile picture that the `/pp/` route was returning was making it difficult for the browser to cache the images- if it's caching based on url and the url that ends up in the cache is the redirect-to-url, then it may not recognize `/pp/<id>` as related and reload every time.

## Solution

1. I manually cached the path to the file on-disk so that the users don't get queried every time
2. I also streamed the file back to the browser directly rather than returning a redirect to it

Other than just avoiding mass-mention posts, this seems like it's about as good as it's going to get. 

Just as a totally made-up estimate, here is a table with the average load over 12 **non-idling spikes**. I'm considering a non-idling spike to be anything >2.0% usage. I caused the spikes by refreshing (with and without the cache enabled in the browser) at roughly equal rates (eyeballed based on the tick rate of the `top` utility).

| Average Load  | Server Cache? | Browser Cache? |
| --                      | --                       | --                         |
|  46.775            | No                     | No                       |
|  35.300            | No                     | Yes                      |
|  31.830            | Yes                    | No                       |
|  25.900            | Yes                    | Yes                      |

Anecdotally, the caching server-side and client-side feels the fastest- it averages around 2-2.5s to a completely loaded page, where caching only client-side or not at all averages around 4-5s.

**Comment by mjhouse** [comment]
Fixed the mention inserts on the server-side in 8237ef5fc8c9744490d877445829f0c27f08e694 and ea98d51fb200aea5773e6bedb1149d97a2185c4a by creating a new `get_users` function and batching all of the user lookups into one query. Submitting a post with ~500 mentions doesn't take more than a second or so now.

**Comment by mjhouse** [comment]
This issue will be resolved when #108 is merged

**Comment by mjhouse** [comment]
I'm not sure I would call this resolved, since we still have problems with large numbers of mentions, but I think that's unavoidable- any time the frontend has to hit up the server hundreds (or thousands) of times from a single page view, that's going to be a CPU usage spike. See #115 for additional work on this problem.

**Comment by zorbathut** [comment]
I'd be interested in digging into this more - like, serving static files should be basically free, even if we end up needing to run a little static-image site based on nginx or something with really aggressive client-side caching. But I also don't think this is something we need to worry about a ton right now :V

**Comment by zorbathut** [comment]
(we'll wait until the site catches on fire I guess)

**Comment by mjhouse** [comment]
lol

**Comment by painejohn** [comment]
> I'd be interested in digging into this more - like, serving static files should be basically free, even if we end up needing to run a little static-image site based on nginx or something with really aggressive client-side caching. But I also don't think this is something we need to worry about a ton right now :V

 I can take a stab at this. Getting nginx running alongside gunicorn or putting gunicorn behind nginx and having nginx serve static assets shouldn't be hard (famous last words :crossed_fingers: )
