### ISSUE TITLE
Polls don't work

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#138]
Did we break it with a formatting change? Is it an easy fix?

Fix it if it's easy!

If it's not easy, remove it from the Formatting page and bump this to P2 or P3.

**Comment by TLSM** [comment]
Look to have been removed in https://github.com/themotte/rDrama/commit/3c2871dd0f5e9c98ba71009de91cb1bd3549cf6a — the bits iterating over `options` and `choices` and creating AUTOPOLLER and AUTOCHOICE comments. Also the clientside Markdown preview doesn't handle `&&foo&&` and `$$bar$$`; unsure if that was removed or if we hadn't added it by time of forking.

Easy option: restore those bits to the submit/edit post/comment routes, and appropriately adjust them for the filter changes they were removed with.

Cleaner option: you'll notice that polls work by creating hidden comments which use their upvote counter to count poll selections. This creates lots of weird edge cases and is otherwise highly inelegant. We replaced this on the upstream some time ago with proper database tables tracking polls, options, and votes. Unsure how much of that would be easy to port over and if it's worth the trouble.

**Comment by JulianRota** [comment]
Interesting. I had been looking into moving the existing-style polls with entries as comments into a cleaner code architecture, but if the backend has already been redone, it's probably best to not spend time on that.

With that, it sounds like it's best to remove it from the formatting page and look into how to port over the updated poll architecture later. AFAIK, polls aren't intended to be a huge thing in the Motte world anyways.

**Comment by zorbathut** [comment]
Yeah I'd be totally fine just pulling it from the Formatting page for now. There's more important things to work on.

Leaving this up to edit to the Formatting page, but as soon as someone does this I'll probably bump it to P4.
