### ISSUE TITLE
Bans do not appear to work.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#215]
See https://www.dev.themotte.org/post/53/who-wants-to-be-banned

**Comment by TLSM** [comment]
I can't replicate this locally, and the logic in both the User model & the posting/commenting routes looks correct to me. If I have Alice (admin) ban Bob for e.g. 0.5 days, Bob gets a "You can't perform this action while banned." toast when trying to comment and the same text error in the footer when trying to post. This works both when banning from the user's profile and from post/comment actions.

I'm almost wondering if this was some strange fluke of the users commenting during periods they weren't banned, or something else weird. However, discovered two issues while trying to investigate this:
1. The /log (alt: /modlog) route is 500'ing on prod. See #216
2. Timestamp detail mouseovers/titles don't work on posts/comments, ex: hovering over "7d ago" doesn't display the actual timestamp "Fri Aug 19 2022 09:55:00 GMT-0400" or as appropriate for one's local timezone. … I'm pretty sure this is another JS load order bug, since I fixed it on upstream a while ago. ~~Will make a real issue if I don't PR it ASAP.~~ PR #217

**Comment by zorbathut** [comment]
This appears to be fixed, although we're not really sure what fixed it.
