### ISSUE TITLE
Flask limiter error

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#222]
![image](https://user-images.githubusercontent.com/160754/187051099-ed267500-602e-4758-bef8-c024ac10ef18.png)

I'm not really sure what's happening here, but it's probably thanks to a recent change, most likely https://github.com/themotte/rDrama/commit/de4d923b32fda1ee39ace9ab1977321b36d986e5 .

This is higher priority than you would expect because it's messing up the debug log.

**Comment by TLSM** [comment]
Think I troubleshooted this one locally. Multi-part bug:

Proximal cause is de4d923b32fda1ee39ace9ab1977321b36d986e5 but for somewhat strange reasons: flask-limiter has almost certainly been trying to generate those errors forever, but they didn't start appearing until routes/static.py began to `import logging`.

When the /log route reaches `if kind not in ACTIONTYPES: logging.warning(f'Unfamiliar ACTIONTYPE {kind}')`, it almost always throws a warning. This logging conditional should probably be removed anyway: the `kind` variable it checks is the one passed with the request based on user input, which is used to filter the modlog listing to only a particular kind. `kind == None` is the expected default case for an unfiltered listing, but `None` will never be in `ACTIONTYPES`.

However, because `logging` was initialized, you now get flask-limiter errors. This (somewhat vague) log entry comes from this [excerpt from flask-limiter](https://github.com/alisaifee/flask-limiter/blob/96de55ad3eef6d11cea594d2c8f57c69981b0d30/flask_limiter/extension.py#L932-L937):
```py
args = [limit_key, limit_scope]
if not all(args):
    self.logger.error(f"Skipping limit: {lim.limit}. Empty value found in parameters.")
```
I believe this is because in `__main__.py`, we define the `key_func` (from which `limit_key` is derived): https://github.com/themotte/rDrama/blob/de4d923b32fda1ee39ace9ab1977321b36d986e5/files/__main__.py#L67-L73

If you don't have a `CF-Connecting-IP` header present on the request (as neither prod nor one's localhost testing environment does), `limit_key = None`.

About to PR this fix.
