### ISSUE TITLE
Combine "Reported Posts" and "Filtered Posts" into one page ("Pending Mod Actions"?)

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#232]

**Comment by zorbathut** [comment]
god this is a pain

Also: Reported Comments and Filtered Comments.

**Comment by TLSM** [comment]
Do you want this in addition to the existing {Reported, Filtered} ⊗ {Posts, Comments}, or cannibalize those and reduce it down to just two: "Pending Mod Actions - {Posts, Comments}"?

Very easy fix otherwise: one-line change in each of the routes to check for `Submission/Comment.filter_state.in_(('filtered', 'reported'))` and change some words in the templates.

**Comment by zorbathut** [comment]
I think the idea is to cannibalize it and reduce it down to just one: Pending Mod Actions. I'm not sure we actually want more than one.

If it's much easier to reduce it down to two first, that would be a good first step, though.

**Comment by zorbathut** [comment]
y'know now I'm kind of rethinking this.

Uh . . . lemme mull over that one.

**Comment by zorbathut** [comment]
Yeah, changed my mind on this one, I think it's fine as-is!
