### ISSUE TITLE
Make a dark-on-light theme, set it to default.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#24]
Yes, I am going to insist that dark-on-light be the default. This is a friendly place!

Make a new theme (copy the Light theme), rename it to Motte, make it the default for new users.

If you then want to refine the theme so it looks a little better and more professional, go for it. If you're not up for that, make a new issue or just make a note on this one and ping Zorba.

**Comment by JamPaladin** [comment]
I will attempt this one!

Edit:
Less simple than first sight - but a good first ticket!

Theme are stored in files\assets\css - I coped light into the new TheMotte theme. Not a design guy, someone better than me can try that part. I'll open a new issue as Zorba requested above

The default theme for new users/not signed in is set in _main_.py - It pulled your system environment variables if available for default, otherwise used the midnight theme. I've removed the check and forced to the new theme.

The default theme for a logged in user is controlled by the user class in \classes\user. It used the same check as above - I've removed the check and forced to the new theme.

The hard part was getting the theme to appear in the user settings menu - this is actually hard-coded in \templates\settings_profile.html. I am new to flask but I would expect there's a way to have this pull from a list instead of hardcoding it - should I open an issue for this?  In either case, I added our default to the front of the list.

Off to try and make my first pull request - it's exciting being part of something!
