### ISSUE TITLE
Comment permalinks should go to that comment

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#261]
This is difficult because what we really need here is a "comment page", that starts at a specific comment; right now we just have "post pages" that list all the comments.

This would also fix/mitigate #191 which is basically an artifact of not having a Comment Page.

**Comment by zorbathut** [comment]
As an example of why this is a problem, https://www.themotte.org/post/2/culture-war-roundup-for-the-week/1158?context=8#context - you have to click on More Posts just to see it.

**Comment by zorbathut** [comment]
Actually, y'know what, I think it might just be that the default context is way too high.

Alright I'm leaving this here for now so we can talk about solving these problems in general - but we already seem to have a comment page!

**Comment by TLSM** [comment]
Comment page for that one, for reference: https://www.themotte.org/comment/1158#context

The one thing that our system can't really do that reddit could was show context _only_ of parents. The current behavior which shows siblings at multiple levels is often convenient, of course, but given the unique requirements of the CW Megathread, it may be worth either revising how the existing `/post/<pid>/-/<cid>?context=N` logic works or having `/comment/<cid>?context=N` (currently the same behavior as the former route) only show lineal parents, and then expose that in the UI somewhere—perhaps replacing the existing Context button.

**Comment by TLSM** [comment]
Brainstormed design in Discord. End decision is, essentially, have `/post/<pid>/-/<cid>` (the usual Context route) act like reddit does and 1) not show siblings, 2) show a limited number of parents. Also, change `/comment/<cid>` to redirect that route, which mostly matters for how `/comment/` is used in modlog sometimes.

Outstanding question about what to do with the "More Comments" button (because of #191). Thinking we'll leave desktop behavior unchanged at present—it's not terribly onerous for a desktop user to click on Context if things start getting too deep, and changing Context behavior means that'll reset nesting level for them. Mobile is less certain: might make "More Comments" there act like a Context button; otherwise, may pull Context out of the ellipsis post_actions_mobile menu for easier access.
