### ISSUE TITLE
user css visible to others

### ISSUE THREAD

**Issue by devonandchris** [themotte/rDrama#273]
I'm not sure anyone would have anything private in their CSS, but I'd start with the assumption that a user's CSS should be restricted to only being viewable by them.

**Comment by TLSM** [comment]
For whomever takes this:

The upstream some time ago replaced the `<link rel="stylesheet" href="/@{{v.username}}/css">` tags with `<style>{{v.css | safe}}</style>`, since they were always included in contexts where we already were guaranteed a User object `v`, and since there's no stored XSS risk—it's applying someone's own CSS only to himself. With that sort of fix, the entire `GET /@username/css` could be gutted. This also saves a request from the browser and saves a database transaction.
