### ISSUE TITLE
Screen may slowly move when typing deep inside a thread.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#279]
https://www.themotte.org/post/30/bugs-suggestions-and-small-comments/1888?context=8#context

I suspect repro steps on this one will be important.

**Comment by devonandchris** [comment]
It is happening to me deep in the AMC stock thread. I suspect Bootstrap because when I activate the debugger and then click in the comment box I end up in that minified file and can't usefully debug further.

Is there a setting to get non-minified JS files? I might be able to exempt things from the 
debugger if this works like a normal debugger.

**Comment by devonandchris** [comment]
Also it stops if my cursor makes it all the way to the bottom of the screen.

**Comment by zorbathut** [comment]
We actually don't even have a non-minified version of bootstrap. We absolutely should, but we currently don't.
