### ISSUE TITLE
Figure out what's up with sporadic test failures

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#326]
https://github.com/themotte/rDrama/actions/runs/3033870958/jobs/4882387631

This one's probably going to be finicky.

**Comment by faul-sname** [comment]
In `util/run_test.py`, we do
```python
def run_test(args):
    result = _operation("tests",[
        "cd service",
        "FLASK_APP=files/cli:app python3 -m flask db upgrade",
        "python3 -m pytest -s",
    ])
```

`_operation()` checks whether the containers are started, and if not calls down to `_start()`, defined as
```python
def _start():
    command = ['docker-compose','up','--build','-d']
    result = _execute(command,check=True)
    time.sleep(1)
    return result
```

In `supervisord.conf`
```
command=sh -c 'FLASK_APP=files/cli:app python3 -m flask db upgrade && gunicorn files.__main__:app -k gevent -w 1 --reload -b 0.0.0.0:80 --max-requests 1000 --max-requests-jitter 500'
```

I suspect what's happening here is that if the timing is exactly right, the `time.sleep(1)` in `_start()` finishes between when the `flask db upgrade` from starting the service creates the `alembic_version` table and when the db upgrade completes, and so the `flask db upgrade` in `run_tests()` tries again to create the `alembic_version` table, and fails because the table already exists.

I think the root cause is you're really not supposed to have a supervisord service definition that includes an `&&` -- if we can figure out how to specify "this should run before `command`", that would be ideal.

Failing that, we could modify the `_start()` function to just poll for `alembic_version()` to exist, or figure out some way to acquire a lock when we start running migrations and release that lock when the migrations finish or fail -- `_start()` could then try to acquire said lock.

**Comment by DinoInNameOnly** [comment]
I attempted to solve this one using my understanding of @faul-sname's analysis by simply replacing the `&&` in `supervisord.conf` with a semicolon. @zorbathut explained why that's probably not the best solution. Pasting his comment below. I don't have plans to work on this right now.

>I think faul's interpretation of the problem is correct, but I'm not sure the actual issue is the &&. Even if that is an issue, changing it to ; isn't a step in the right direction; it's still running two commands, but now it isn't reporting failure on the first one, which is not the way we want to do it.

>What we should do is figure out some way to disable supervisord in test mode. If this wasn't docker-compose, that would be as easy as just calling the container with a custom command, problem solved. But it is docker-compose! Which makes this all a little bit gnarlier.

>I think the right solution here is to intercept the docker-compose file and modify it:

> * Find a Yaml parser
> * Parse the docker-compose.yml
> * Change the "run" command for themotte (you'll have to add a parameter here)
> * Save it out to a file (docker-compose-test.yml?)
> * Run docker-compose pointing at that file
> * Now we have a working environment that isn't even running supervisord, and therefore isn't trying to start the server, and that's a perfect playground for test.py to muck around and do whatever it wants in.

>I dunno if you're up for that, it's definitely more work :)
