### ISSUE TITLE
Multi-level lists display properly on the comment preview, but not in the comment

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#336]
See https://www.themotte.org/post/30/bugs-suggestions-small-comments-and-site/6766?context=8#context

**Comment by faul-sname** [comment]
I found the [commit](https://github.com/Butonix/ruqqus-1/commit/1661e3d2b926296afc88c9a3490873d086194418) that introduced the CSS which causes nested lists not to indent properly.

Trying to figure out why it was added in the first place, but I think the issue is just that an overly-broad rule was applied there.

**Comment by faul-sname** [comment]
Welp, I have no idea why it was put in there but that sure is the culprit.

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/95843830/190839955-588efba2-a0cb-4c90-b913-7438f485f0ec.png) | ![image](https://user-images.githubusercontent.com/95843830/190839987-0df85ece-cb3b-4b31-9086-8947c0a89f0e.png) |
