### ISSUE TITLE
@-links don't work if the user has an underscore in their username

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#398]
The ping works, though!

See https://www.themotte.org/post/159/quality-contributions-report-for-october-2022/25545?context=8#context .

**Comment by virtual256** [comment]
I've started digging into this and have found a likely spot where this is breaking.

The behavior for pings happens via a call to `get_user()`, while the `@-link --> [@username]<http://themotte.org/id/{userid}>` functionality seems to be going through the `get_users()` function instead.  Both of these are in `helpers/get.py`, btw.

In both cases, the usernames are sanitized via calls to `sql_ilike_clean()` in `string.py`

These two functions use slightly different filters, and that seems to be enough to trigger the bug:

`get_user(username: str)`:
```python
user = g.db.query(User).filter(
	or_(
		User.username.ilike(username),
		User.original_username.ilike(username)
		)
	).one_or_none()
```

`get_users(usernames: Iterable[str])`:
```python
users = g.db.query(User).filter(
	or_(
		User.username == any_(usernames),
		User.original_username == any_(usernames)
		)
	).all()
```

`User.username == "namewithoutunderscore"` works the same both ways, as the sanitizer doesn’t change the username.

`User.username == "name_with_underscore"` breaks in `get_users()` as the sanitizer makes the username `"name\\_with\\_underscore"` instead and `"name_with_underscore" == "name\\_with\\_underscore"` is `False`.

I'm currently looking into how to get `.ilike()` functionality with multiple elements in an Iterable at once, though I could see there being a problem with the sanitizer being called on an already sanitized string if that's happening.

**Comment by zorbathut** [comment]
So from what I understand, the only reason `ilike` is being used is because it provides case-insensitive compare. And there's apparently a better way to do this. So I think the right solution here may be to dump `ilike` entirely, as well as the `sql_ilike_clean()` function, and use whatever the appropriate case-insensitive-compare functionality is.

But I don't know what that is offhand.

I'd check sqlalchemy documentation for that.

**Comment by virtual256** [comment]
By my reading, `like`/`ilike` do a pattern match search, with an optionally specifiable escape char, `_` as a single char wildcard match  and `%` as a multi-char wildcard match.  `like` versus `ilike` differ only by case intensivity.

My gut says the issue is with doing an exact match in `get_users()` and it falling with the added escape `\` chars, as `"under_score" == "under\\_score"` returns `False`.

I'm planning to dig into the markdown parsing code and see how things are being called to see if there's something funky happening there that's more fundamental.

**Comment by zorbathut** [comment]
They do! But I think the only thing we're actually using that for is the case-insensitive matching - if you check out `sql_ilike_clean()` it's basically just escaping the characters so they can be used in ilike and nothing more. So we could just bypass the relatively-complicated `ilike` and do a simple case-insensitive match.

**Comment by virtual256** [comment]
In which case, lemme try a quick fix and see if that solves the issue.

**Comment by virtual256** [comment]
My first attempt at a quick fix didn't work, but I've now found more detail as to what is going wrong and how to fix it!

I went into postgres and tried the queries we're using in `get.py` with the string returned from `sql_ilike_clean()` on a username with an underscore:

```
In [1]: def sql_ilike_clean(my_str): 
   ...: ^Iif my_str is None: 
   ...: ^I^Ireturn None 
   ...: ^Ireturn my_str.replace(r'\\', '').replace('_', r'\_').replace('%', '').
   ...: strip() 
   ...: 

In [2]: username = 'under_score' 

In [3]: sql_ilike_clean(username) 
Out[3]: 'under\\_score'
```

```
postgres=# select * from users where username like 'under\\_score';
(0 rows)

postgres=# select * from users where username like 'under\_score';
-[ RECORD 1 ]--------------+-----------------
id                         | 10
username                   | under_score
.
.
.
```

This is basically the smoking gun I was looking for pointing at the `get_users()` comparison using `sql_ilike_clean()` as the issue, where python doesn't play nicely with raw strings, returning `"under\\_score"` instead of `"under\_score"`.

Reworking the query to use `func.lower(User.username)` gives formatted URLs as expected!

I'm going to build a test case to check for the expected functionality and validate that my fix works, then plan to submit a pull request with the fix.

More broadly, if we're only using the `sql_ilike_clean()` function to do a lowercase comparison, it's worth changing the other 7 places it's used and changing those as well, then removing the function entirely.  Should that be a different pull request?

**Comment by zorbathut** [comment]
I think "remove `ilike` matching everywhere, which also fixes this bug" is a reasonable single pull request :)

That sounds like a good approach, though I'd recommend `func.lower()`ing both sides of it just for the sake of paranoia. (Which you may already be doing.)

**Comment by virtual256** [comment]
The db side gets `func.lower()`, as that also casts it to a string at the same time.  The other side gets a regular `username.lower()` string call.
