### ISSUE TITLE
Improve TheMotte theme a bit.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#48]
This is probably on Zorba because he doesn't even know what needs to be done yet, but if you're a CSS wizard and can see what I'm looking at when I say it seems a bit unnecessarily hard to read, feel free to give it a shot!

**Comment by mjhouse** [comment]
Using colors based around [this](https://coolors.co/1a6187).

**Comment by mjhouse** [comment]
### Notes

This comment will be edited and kept as a list of changes that were made in response to this issue. This helps me, because I will forget anything that I don't write down, and it helps anyone who may need to undo my changes in the future.

### Changelist

* Moved title of posts in post listing above username and time
* Moved time ahead of username (`8m ago by <name>` instead of `<name> 8m ago`)
* Removed `stretched-link` class that caused title link to override username/usernote links (clicking anywhere on a post list element went to the post)
* Commented out the "Mark distinguished" and "Mark club" options on post listings
* Commented out the "Copy link" and "Votes" links on post elements. Link can be copied by visiting the post and taking it from the url bar, votes is unnecessary since you can see them on the left anyway.
* Replaced `default_thumb_link.webp`
* Replaced `default_text.webp`
* Removed GIF button in comments.html and submission.html
* Added a check to get rid of an error in `marked.custom.js`:196
* Restructured the placeholder comment message html (`submission.html`:562) and added some code to remove it (`comments_v.js`:246) when a reply is submitted (because the comment section isn't empty anymore)
* Vertically centered username text in dropdown menu at top right
* Removed Donate button from dropdown menu at top right
* Changed color of collapse sidebar
* Removed store and chat icons on mobile view of page
* Changed all "Simps"/"Haters" stuff to "Upvoters"/"Downvoters" 
* Reworked contact form a bit
* Removed Profile Anthem section from settings page
* Removed Name Color section from settings page
* Removed Enemies section from settings page
* Removed PayPig button from Settings > Security > Email

**Comment by mjhouse** [comment]
I made some calls on removing/changing html from the site, which seems out of scope for this issue (which refers only to the theme). I'm going to explain:
1. Why I think these structural changes should go under this issue
2. What exactly I changed
3. Why I changed each thing that I changed

## Why these changes should go under this issue

There are a large number of small changes scattered everywhere and it seemed reasonable to just deal with them since I was there anyway. For many of them, the CSS would need to change a bit as well, and it seemed better to get them while I was already changing the styles than to bounce back and forth between issues for structural changes vs fixes for styles.

## What exactly changed

* Removed out the "Mark distinguished" and "Mark club" options on post listings
* Removed out the "Copy link" and "Votes" links on post elements
* Removed Donate button from dropdown menu at top right
* Removed Store and Chat icons on mobile view of page
* Removed Profile Anthem section on settings page
* Removed Name Color section on settings page
* Removed Enemies section on settings page
* Removed PayPig button from Settings > Security > Email

## Why I changed them

#### Commented out the "Mark distinguished" and "Mark club" options on post listings (the `...` dropdown)

I don't *think* that "Mark distinguished" is going to be useful on TheMotte, but I could be wrong. I'm more sure that we're not going to have all the "Country Club" stuff, though. Since I wasn't sure about "Mark distinguished", I commented these rather than remove them.

#### Commented out the "Copy link" and "Votes" links on post elements

These seemed like redundant clutter- you can get the link from the url bar, and the votes are already prominently displayed on the post. 

#### Removed Donate button from dropdown menu at top right

Unless I've been misinformed, TheMotte isn't going to be accepting donations (right now, anyway).

#### Removed Store and Chat icons on mobile view of page

Chat didn't work and is going away, probably. Store is definitely not going to happen.

#### Removed Profile Anthem section on settings page

I don't think that having an autoplay video in a profile contributes much to the site or really improves the discussion. I guess it gives users another option to customize their profile, so I guess an argument could be made for keeping it.

#### Removed Name Color section on settings page

I removed the name color because I think it's likely that we'll want colors that mean things- special colors for mod usernames, OP usernames etc. and letting people set their own makes that impossible.

#### Removed Enemies section on settings page

I removed the Enemies section but left the Friends section because I don't think letting users put together hate-lists is a good way to improve discussion.

#### Removed PayPig button from Settings > Security > Email

Unless I've been misinformed, TheMotte isn't going to be accepting donations (right now, anyway).

**Comment by mjhouse** [comment]
Pull request #102 is up

**Comment by mjhouse** [comment]
Resolved by #102
